-- My Code
SELECT RAI.NAME
FROM (
         SELECT RANK() OVER(order by AI.DATETIME) RANK, AI.NAME
         FROM ANIMAL_INS AI
     ) RAI
WHERE RAI.RANK = 1


-- Answer Code
SELECT A.NAME
FROM (SELECT NAME, DATETIME
      FROM ANIMAL_INS
      ORDER BY DATETIME
     ) A
WHERE ROWNUM = 1